[package]
name = "loopcore"
version = "0.1.0"
edition = "2021"

[dependencies]
jack = "0.13.2"
serde = "1.0.219"
serde_bytes = "0.11.17"
serde_derive = "1.0.219"
serde_osc = { git = "https://github.com/snailmusic/serde_osc.git" }
